### PR TITLE
Fixes #RHIROS-1284 - Dynamically create table partitioning to optimiz…

### PR DESCRIPTION
**Pull request by patilsuraj767**
…e DB performance

### CODE REVIEW

**Comment by patilsuraj767** [comment]
Migrations in this PR will create the postgres functions and triggers. Whenever new data is inserted in the workload table postgres trigger `workload_metrics_insert_trigger` will be triggered and it will execute the function `workload_metrics_insert_trigger_func`. 
`workload_metrics_insert_trigger_func` based on the `metrics_upload_at` timestamp will dynamically create the partition for table `workload_metrics`.

**Comment by kgaikwad** [comment]
@patilsuraj767  - could you update ticket number to [RHIROS-1347](https://issues.redhat.com/browse/RHIROS-1347)?

**Comment by patilsuraj767** [comment]
Created new PR here - https://github.com/RedHatInsights/ros-ocp-backend/pull/127

**Pull request closed without merging**
