### PR TITLE
[Do not merge] - PR to trigger tests on EE against ROS OCP with latest Kruize RM image

### PR DESCRIPTION
**Pull request by patilsuraj767**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by chandrams** [comment]
Created this for testing, closing it

**Comment by kgaikwad** [comment]
As it is test PR, confirmed by @chandrams closing this PR.

**Comment by pgarciaq** [comment]
## Backend Verification — `group_by` Support Across Endpoints

### Summary Table

| Endpoint | `group_by[cluster]` | `group_by[project]`/`namespace` | `group_by[node]` | Notes |
|----------|----|----|----|----|
| VM list (`/vms`) | **Not supported** | **Not supported** | **Not supported** | Handler has no grouped response logic at all |
| GPU MIG (`/gpu/mig`) | **Not supported** | **Not supported** | N/A | Handler returns flat paginated list only |
| GPU Time-Slicing (`/gpu/time-slicing`) | **Not supported** | N/A | N/A | Handler returns flat paginated list only |
| PVC list (`/pvcs`) | **Supported** | **Supported** | N/A | Uses `parseStorageListGroupBy` in `handlers_storage_groupby.go` |
| Snapshot list (`/snapshots`) | **Supported** | **Supported** | N/A | Same `parseStorageListGroupBy` logic |
| Node list (`/nodes`) | **Not supported** | N/A | N/A | Handler (`handlers_node_utilization.go`) has no group_by logic |

### Details

**Endpoints with `group_by` support:**
- **PVC** and **Snapshot** endpoints share group_by logic in `internal/api/handlers_storage_groupby.go` via `parseStorageListGroupBy()`.
- Supported values: `group_by[cluster]`, `group_by[project]`, `group_by[namespace]` (namespace is alias for project).
- Constraint: `group_by[cluster]` and `group_by[project]` cannot be combined (returns 400 error).

**Endpoints WITHOUT `group_by` support (need backend work):**
- **VM list** (`handlers_vm_recs.go`): No call to `queryparams.GroupByField` or any grouped response variant. Returns a flat paginated list.
- **GPU MIG** (`handlers_gpu_mig.go`): Same — flat paginated response only.
- **GPU Time-Slicing** (`handlers_node_recs.go`): Same — uses triple-cursor pagination, no grouped mode.
- **Node list** (`handlers_node_utilization.go`): Flat list with cursor-based pagination. No group_by parsing.

### What's needed for unsupported endpoints
To add `group_by` support to VM, GPU, or Node endpoints, the pattern from PVC/Snapshot could be reused:
1. Parse `group_by` param via `queryparams.GroupByField`
2. Execute a grouped SQL query (aggregate + COUNT + SUM)
3. Return a different response shape (grouped envelope vs. flat list)

### Code locations
- Existing group_by logic: `internal/api/handlers_storage_groupby.go`
- Group_by param parsing: `internal/api/queryparams/queryparams.go` (`GroupByField`)

**Comment by pgarciaq** [comment]
## Implementation Complete — `group_by` support for Node, GPU, and VM tabs

**Branch:** `pgarciaq-rosocp-superpowers-phase15` (both `ros-ocp-backend` and `koku-ui`)

### Backend (ros-ocp-backend)

New grouped query handlers following the existing Storage/Quota `group_by` pattern:

| Endpoint | `group_by` params | Aggregation |
|----------|------------------|-------------|
| `GET /recommendations/openshift/nodes` | `group_by[cluster]` | COUNT nodes, SUM savings |
| `GET /recommendations/openshift/gpu/time-slicing` | `group_by[cluster]` | COUNT recs, SUM savings |
| `GET /recommendations/openshift/gpu/mig` | `group_by[cluster]`, `group_by[project]` | COUNT recs (no savings) |
| `GET /recommendations/openshift/vms` | `group_by[cluster]`, `group_by[namespace]` | COUNT recs, SUM savings |

**New files:**
- `internal/api/handlers_node_utilization_group.go`
- `internal/api/handlers_node_recs_group.go` (GPU TS)
- `internal/api/handlers_gpu_mig_group.go`
- `internal/api/handlers_vm_recs_group.go`
- `internal/api/handlers_groupby_test.go`

**Modified files:**
- `internal/api/handlers_node_utilization.go` — conditional branch to grouped handler
- `internal/api/handlers_node_recs.go` — conditional branch for GPU TS
- `internal/api/handlers_gpu_mig.go` — conditional branch for GPU MIG
- `internal/api/handlers_vm_recs.go` — conditional branch for VM
- `openapi.json` — documented all new `group_by` parameters

### Frontend (koku-ui)

Reused the existing `OptimizationsStorageGroupByToolbar` component for all four tabs:

- **Node tab:** `group_by[cluster]` with drill-down
- **GPU Time-Slicing tab:** `group_by[cluster]` with drill-down
- **GPU MIG tab:** `group_by[cluster]` and `group_by[project]` with drill-down
- **VM tab:** `group_by[cluster]` and `group_by[namespace]` with drill-down

Each tab's table/toolbar/dataTable components were updated to:
1. Render grouped columns (group key, count, savings) when `group_by` is active
2. Render normal detail columns when `group_by` is absent
3. Support drill-down from grouped rows (clicking a group adds it as a filter)
4. Persist `group_by` selection in URL state

### Notes
- `group_by[node]` was removed from VM because the `vm_recommendations` table lacks a `node` column
- GPU MIG grouped results do not include savings (consistent with the MIG data model which has no savings field)
- Unit tests added for `parseGPUMIGListGroupBy` and `parseVMListGroupBy` parsing functions

**Pull request closed without merging**
