### PR TITLE
RHINENG-12346 Add resource unit query parameters to list recommendations api endpoint

### PR DESCRIPTION
**Pull request by chambridge**
## PR Title :boom:

Add resource unit query parameters to list recommendations api endpoint

## Why do we need this change? :thought_balloon:

* Add unit selection query parameters

## Documentation update? :memo:

- [ ] Yes
- [ ] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Does this change depend on specific version of Kruize
  - If yes what is the version no:
  - [ ] Is that image available in production or needs deployment?
- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

### CODE REVIEW

**Comment by kgaikwad** [comment]
Hello @chambridge - With latest discussion with UX and PM on https://issues.redhat.com/browse/RHINENG-10671, it is concluded that ROS OCP will send unit strings in "Kubernetes" format and enhance current behavior by adding param that allows users to select in which format Kubernetes/True unit they want API to respond usage values and unit strings. 

I see you extended existing param options so will it be possible to share your thoughts on above ticket? This will be helpful. Thanks!

**Comment by chambridge** [comment]
> Hello @chambridge - With latest discussion with UX and PM on https://issues.redhat.com/browse/RHINENG-10671, it is concluded that ROS OCP will send unit strings in "Kubernetes" format and enhance current behavior by adding param that allows users to select in which format Kubernetes/True unit they want API to respond usage values and unit strings.
> 
> I see you extended existing param options so will it be possible to share your thoughts on above ticket? This will be helpful. Thanks!

I have commented on that issue. The current resolution works for me, but I'd prefer it was extended to the list endpoint as well.

**Review by saltgen — APPROVED** [review]
LGTM 👍🏼 @chambridge Shall I merge this?

**Comment by chambridge** [comment]
sure.

**Pull request merged**
