### PR TITLE
Delete partitions

### PR DESCRIPTION
**Pull request by msvinaykumar**
Remove partitions that exceed the specified threshold days set to (16 days) using ENV : deletepartitionsthreshold . which run  on 16th of every month at midnight.

### CODE REVIEW

**Comment by kgaikwad** [comment]
Hello @msvinaykumar, thanks for this change! Do you have any JIRA reference to this change to attach?

**Comment by patilsuraj767** [comment]
Hello @msvinaykumar, I can see kruize side PR is till open - https://github.com/kruize/autotune/pull/1076
Will this cronjob still work without having the above mentioned PR merged in Kruize? Will it be correct to consider above PR as a dependency for this PR?

**Comment by PreetiW** [comment]
@patilsuraj767 just wanted to check if this PR is still relevant?

**Comment by patilsuraj767** [comment]
> @patilsuraj767 just wanted to check if this PR is still relevant?

Yes it is. Once Kruize side of changes are released in 0.0.20.2 we can resume the work on this PR.

**Review by patilsuraj767 — APPROVED** [review]
PR check is failing due to some other issue but I have manually tested in EE, cronjob is getting successfully created in OpenShift hence merging the PR. 
Thanks @msvinaykumar

**Pull request merged**
