### PR TITLE
remove machine_pool from clowdapp files

### PR DESCRIPTION
**Pull request by kgaikwad**

### CODE REVIEW

**Comment by kgaikwad** [comment]
@patilsuraj767 - Do you think we should apply this change?

**Comment by kgaikwad** [comment]
@patilsuraj767 / @saltgen - do you think this change needed? OR may I close this pull-request?

**Comment by patilsuraj767** [comment]
@kgaikwad I think `machinePool` is stale parameter which we do not use in our current configuration. I don't is any harm in merging the PR.

**Review by saltgen — APPROVED** [review]

**Comment by kgaikwad** [comment]
Thanks @patilsuraj767 and @saltgen for merging PR.

**Comment by pgarciaq** [comment]
## Backend Filter/Group_by Verification — VM List (`GET /recommendations/openshift/vms`)

Verified against `internal/api/handlers_vm_recs.go` (handler: `GetVMRecommendations`).

| Parameter | Status | Notes |
|-----------|--------|-------|
| `filter[node]` | **Not supported** | The VM handler does not parse a `node` filter. VMs are filtered by `cluster`, `project` (namespace), `vm_name`, `term`, `engine`, `confidence`, `guest_os`, `gpu_classification`, and boolean flags. No node-level filtering. |
| `filter[is_idle]` | **Supported** | Parsed via `parseVMRecBoolFilter(c, "is_idle")` at line 228. Applied to `engine.VMRecommendationFilters.IsIdle`. |
| `filter[is_abandoned]` | **Supported** | Parsed via `parseVMRecBoolFilter(c, "is_abandoned")` at line 237. Applied to `engine.VMRecommendationFilters.IsAbandoned`. |
| `filter[is_oversized]` | **Supported** | Parsed via `parseVMRecBoolFilter(c, "is_oversized")` at line 232. Applied to `engine.VMRecommendationFilters.IsOversized`. |
| `filter[is_network_bound]` | **Supported** | Parsed via `parseVMRecBoolFilter(c, "is_network_bound")` at line 249. Applied to `engine.VMRecommendationFilters.IsNetworkBound`. |
| `filter[is_power_off_candidate]` | **Not supported** | No filter parsing exists for `is_power_off_candidate`. The field is returned in the response (`vmRecMetadata.IsPowerOffCandidate`) but cannot be filtered on. Would need backend work. |
| `filter[guest_os]` | **Supported** | Parsed via `queryparams.FirstFilter(c, "guest_os")` at line 318. Applied to `engine.VMRecommendationFilters.GuestOS`. |
| `group_by[cluster]` | **Not supported** | The VM handler has no `group_by` logic at all. No call to `queryparams.GroupByField` or `parseStorageListGroupBy`. Would need backend work. |
| `group_by[namespace]` | **Not supported** | Same as above — no group_by support on the VM list endpoint. |
| `group_by[node]` | **Not supported** | Same as above — no group_by support on the VM list endpoint. |

### Summary
- Filters `is_idle`, `is_abandoned`, `is_oversized`, `is_network_bound`, and `guest_os` are **fully supported**.
- Filters `node` and `is_power_off_candidate` are **not supported** — need backend implementation.
- All `group_by` params are **not supported** — the VM handler lacks grouped response logic entirely.

### Code locations
- Handler: `internal/api/handlers_vm_recs.go:170` (`GetVMRecommendations`)
- Bool filter helper: `internal/api/handlers_vm_recs.go:157` (`parseVMRecBoolFilter`)
- Filter struct: `internal/engine/` (`VMRecommendationFilters`)

**Pull request merged**
