### PR TITLE
Fixes #RHIROS-1219 - upgrade Kruize to 0.0.16_rm

### PR DESCRIPTION
**Pull request by kgaikwad**

### CODE REVIEW

**Comment by saltgen** [comment]
Changes are loosely dependent on `current`, [here](https://github.com/RedHatInsights/ros-ocp-backend/pull/95/files#diff-2547f73a975efa6b476ee96cc97b505eb29e89eac79069906d6f5c069c7f20e8R291).

**Comment by kgaikwad** [comment]
> Changes are loosely dependent on `current`, [here](https://github.com/RedHatInsights/ros-ocp-backend/pull/95/files#diff-2547f73a975efa6b476ee96cc97b505eb29e89eac79069906d6f5c069c7f20e8R291).

Created a separate PR #98

**Comment by kgaikwad** [comment]
+ adding @dgaikwad  into loop for testing.

**Comment by kgaikwad** [comment]
Removed `needs testing` label based on offline [conversation](https://redhat-internal.slack.com/archives/C01C1GVT3TP/p1688471335658589?thread_ts=1688456599.311799&cid=C01C1GVT3TP)

**Review by patilsuraj767 — APPROVED** [review]
Thanks @kgaikwad PR looks good to me. 👍 
Just a same thing, can you add `value: '8dd52f3'`  in clowdapp file under 
`KRUIZE_IMAGE_TAG` - [here](https://github.com/RedHatInsights/ros-ocp-backend/blob/main/clowdapp.yaml#L230). Then we can remove `KRUIZE_IMAGE_TAG` from app-interface under EE and stage target so that from future there will be no need to raise separate MR on app-interface to push new image of kruize on stage or EE.

**Pull request merged**
