### PR TITLE
Fixes #RHINENG-2923 - serve variation in percentage form

### PR DESCRIPTION
**Pull request by upadhyeammit**
## PR Title :boom:

Please title this PR with a summary of the change, along with the JIRA card number.

Suggested formats: 

1. Fixes/Refs #RHIROS-XXX - Title
2. RHIROS-XXX Title
3. RHINENG-XXX Title 

Feel free to remove this section from PR description once done.

## Why do we need this change? :thought_balloon:

Please include the __context of this change__ here. If the change depends on Kruize add details about that as well!

## Documentation update? :memo:

- [ ] Yes
- [ ] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Does this change depend on specific version of Kruize
  - If yes what is the version no:
  - [ ] Is that image available in production or needs deployment?
- [ ] Bugfix
- [x] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

### CODE REVIEW

**Review by patilsuraj767 — APPROVED** [review]
Overall PR looks good to me but I am bit concern of parsing kruize recommendation json on multiple places. Not in this PR but maybe we can have separate JIRA task to combine this parsing logic.
If you see the current codebase we are doing almost the same json parsing steps in `convertVariationToPercentage`  and `transformComponentUnits`. 
Suppose kruize changes something in there json object than we will need fix it in multiple places.

**Comment by upadhyeammit** [comment]
> Overall PR looks good to me but I am bit concern of parsing kruize recommendation json on multiple places. Not in this PR but maybe we can have separate JIRA task to combine this parsing logic. If you see the current codebase we are doing almost the same json parsing steps in `convertVariationToPercentage` and `transformComponentUnits`. Suppose kruize changes something in there json object than we will need fix it in multiple places.

Yeah I completely agree to this! its the same thing!

**Comment by upadhyeammit** [comment]
@patilsuraj767 I had meeting with Dan and as per that not updating the format for variation block. At the same time I have confirm about multiple situations about returning a 0.0 from API and what we have implemented now is fine. At the same time we can independently merge and release this pr as UI does not depend on variation now.

**Review by patilsuraj767 — APPROVED** [review]
LGTM 👍

**Pull request merged**
