### PR TITLE
RHINENG-10850 - HTTP Metrics on Grafana

### PR DESCRIPTION
**Pull request by saltgen**
## Why do we need this change? :thought_balloon:

Display the request and response life-cycle metrics between ROSOCP and Kruize on Grafana.

## Documentation update? :memo:

- [ ] Yes
- [x] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Does this change depend on specific version of Kruize
  - If yes what is the version no:
  - [ ] Is that image available in production or needs deployment?
- [ ] Bugfix
- [x] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added

## Additional :mega:

image

### CODE REVIEW

**Comment by upadhyeammit** [comment]
This will need rebase to satisfy the Red Hat Konflux step!

**Review by kgaikwad — COMMENTED** [review]
With updated changes in PR, I can see, new panels are now visible under stage grafana instance. 





Screenshot from 2024-11-18 15-55-50

**Review by kgaikwad — APPROVED** [review]

**Comment by kgaikwad** [comment]
Thank you @saltgen for PR change & quick fixing the issue for stage.

**Comment by pgarciaq** [comment]
## Industry Context for Capacity Constant

The proposed `defaultDigestRowCapacity` of **8,192** is informed by industry container density data:

| Source | Metric | Value |
|--------|--------|-------|
| [CNCF Annual Survey 2025](https://www.cncf.io/reports/cncf-annual-survey-2025/) | Containers per cluster (median) | **~370** |
| [Datadog Container Report 2025](https://www.datadoghq.com/container-report/) | Containers per cluster (median) | **250+** |
| [Datadog Container Report 2025](https://www.datadoghq.com/container-report/) | Top-percentile clusters | **5,000+** |

### Why 8,192?

- With a 30-day lookback: `8,192 ÷ 30 days ≈ 273 containers` — covers clusters at or below the CNCF median without any reallocation
- For a median cluster (~370 containers): `370 × 30 = 11,100 rows` — only 1 doubling from 8,192 (vs. 14 doublings from nil)
- For a large cluster (5,000 containers): `5,000 × 30 = 150,000 rows` — 5 doublings from 8,192 (vs. 18 from nil)
- Initial memory: `8,192 × 240B ≈ 1.9 MB` — negligible even on constrained pods

### Static vs. adaptive

A `SELECT count(*)` pre-query was considered but rejected:
1. The covering index makes it fast (~1ms), but it adds a round-trip per reconcile cycle
2. The doubling strategy handles undersized hints efficiently — eliminating most (not all) doublings is sufficient
3. A static constant avoids runtime complexity and is easier to reason about in performance audits

The constant covers ≥95% of deployments without any reallocation. Clusters above ~270 containers still benefit from eliminating the first 13 of 21 doublings.

See also: [Performance Audit v4 — Appendix: Industry Context for Capacity Constants](../docs/performance/native-engine-audit-v4-2026-07.md)

**Pull request merged**
