### PR TITLE
RHINENG-10277 openapi fixes for iqe

### PR DESCRIPTION
**Pull request by saltgen**
## Why do we need this change? :thought_balloon:

CPU format can be string or null as per business logic; other changes

## Documentation update? :memo:

- [ ] Yes
- [x] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Does this change depend on specific version of Kruize
  - If yes what is the version no:
  - [ ] Is that image available in production or needs deployment?
- [x] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

### CODE REVIEW

**Comment by kgaikwad** [comment]
+ keeping @yash2189  into loop

**Comment by saltgen** [comment]
Posted all changes as far as notifications filtering is concerned, awaiting input/ack from QE.

**Comment by kgaikwad** [comment]
@saltgen, could you please perform rebase?

**Comment by kgaikwad** [comment]
@saltgen - Based on slack [conversation](https://redhat-internal.slack.com/archives/C01C1GVT3TP/p1716386187184929?thread_ts=1716379047.421449&cid=C01C1GVT3TP), could you also update ticket number to [RHINENG-10277](https://issues.redhat.com/browse/RHINENG-10277)?

**Comment by anurag03** [comment]
This PR check result won't be the correct way to validate the PR as we have to re-generate the api-client using new api specs.
@yash2189 please generate the new api-client and validate this PR.

**Comment by yash2189** [comment]
LGTM. Observations have been added on card.

**Review by yash2189 — APPROVED** [review]

**Pull request merged**
