### PR TITLE
Fixes #RHINENG-11015 - Check if month changed while saving recommenda…

### PR DESCRIPTION
**Pull request by patilsuraj767**
…tion

## :guardsman: Checklist :dart:

- [ ] Does this change depend on specific version of Kruize
  - If yes what is the version no:
  - [ ] Is that image available in production or needs deployment?
- [x] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

### CODE REVIEW

**Comment by upadhyeammit** [comment]
Hello!

I just felt the change is bit complex, I gave it a shot,
~~~
package main

import (
	"fmt"
	"time"
  "math/rand"
)

func main() {
  randInt := rand.Intn(5000)
  mockDbDate := time.Now().AddDate(0,0,randInt)
  mockMsgDate := mockDbDate.AddDate(0,0,+1)
  fmt.Println("\nDB date", mockDbDate)
  fmt.Println("Msg date", mockMsgDate)
  
  if needRecommOnFirstOfMonth(mockDbDate, mockMsgDate){
    dbDateMonth := getMonth(mockDbDate)
    msgDateMonth := getMonth(mockMsgDate)
    fmt.Println("DB month", dbDateMonth)
    fmt.Println("Msg month", msgDateMonth)
    if msgDateMonth > dbDateMonth {
      fmt.Println("Generate Recommendations!")
    }
  }
}

func needRecommOnFirstOfMonth(mockDbDate time.Time, mockMsgDate time.Time) bool {
  dbDateMonth := getMonth(mockDbDate)
  msgDateMonth := getMonth(mockMsgDate)
  if isItFirstOfMonth(mockMsgDate) && (msgDateMonth > dbDateMonth){
    return true
  }
  return false
}

func getMonth(d time.Time) time.Month {
  _,month,_ :=  d.Date()
  return month
}

func isItFirstOfMonth(d time.Time) bool {
  _,_,day := d.Date()
   return day == 1
}
~~~

I tried this in loop and I can see it works,
~~~
$ while true; do go run main.go; sleep 1; done

DB date 2027-02-03 22:36:12.240431254 +0530 IST
Msg date 2027-02-04 22:36:12.240431254 +0530 IST

DB date 2025-06-10 22:36:13.330289482 +0530 IST
Msg date 2025-06-11 22:36:13.330289482 +0530 IST

DB date 2025-10-28 22:36:14.420091902 +0530 IST
Msg date 2025-10-29 22:36:14.420091902 +0530 IST

DB date 2027-11-30 22:36:15.506732978 +0530 IST
Msg date 2027-12-01 22:36:15.506732978 +0530 IST
DB month November
Msg month December
Generate Recommendations!

DB date 2031-05-01 22:36:16.595538961 +0530 IST
Msg date 2031-05-02 22:36:16.595538961 +0530 IST

DB date 2036-10-05 22:36:17.678928498 +0530 IST
Msg date 2036-10-06 22:36:17.678928498 +0530 IST

DB date 2029-05-31 22:36:32.897784353 +0530 IST
Msg date 2029-06-01 22:36:32.897784353 +0530 IST
DB month May
Msg month June
Generate Recommendations!

DB date 2032-09-07 22:36:33.989164876 +0530 IST
Msg date 2032-09-08 22:36:33.989164876 +0530 IST

~~~

Let me know if you think we should go with solution similar to this?

**Comment by upadhyeammit** [comment]
> @upadhyeammit This condition - `(msgDateMonth > dbDateMonth)` will fail in one scenario. Consider mockDbDate is 31-12-2024 and mockMsgDate is 1-1-2025 is this scenario above condition will fail and `needRecommOnFirstOfMonth` will return false.

Yep you are correct, below code depends on whole date instead of fraction of it,
~~~
package main

import (
	"fmt"
	"math/rand"
	"time"
)

func main() {
	randInt := rand.Intn(5000)
	mockDbDate := time.Now().AddDate(0, 0, +randInt)
	mockMsgDate := mockDbDate.AddDate(0, 0, +1)
	getDate(mockDbDate)
	if needRecommOnFirstOfMonth(mockDbDate, mockMsgDate) {
		fmt.Println("Generate Recommendations!")
	}
}

func needRecommOnFirstOfMonth(mockDbDate time.Time, mockMsgDate time.Time) bool {
	dbDate := getDate(mockDbDate)
	msgDate := getDate(mockMsgDate)
	fmt.Println("\nDB date timed to 00:00", dbDate)
	fmt.Println("Msg date timed to 00:00", msgDate)
	if isItFirstOfMonth(mockMsgDate) && msgDate.After(dbDate) {
		return true
	}
	return false
}

func getDate(d time.Time) time.Time {
	return time.Date(d.Year(), d.Month(), d.Day(), 0, 0, 0, 0, d.Location())
}

func isItFirstOfMonth(d time.Time) bool {
	_, _, day := d.Date()
	return day == 1
}
~~~

~~~
DB date timed to 00:00 2024-12-30 00:00:00 +0530 IST
Msg date timed to 00:00 2025-01-01 00:00:00 +0530 IST
Generate Recommendations!
~~~

**Comment by patilsuraj767** [comment]
@upadhyeammit This condition `isItFirstOfMonth(mockMsgDate) && msgDate.After(dbDate)` will also fail in a scenario  where msgDate is 1st july 2:00AM and dbDate is 1st july 1:00AM. It will always return true for every report/datapoint which comes on 1st of the month and it will cause recommender-poller service to hit kruize recommendation_api for every report coming on 1st of the month.

**Comment by upadhyeammit** [comment]
> @upadhyeammit This condition `isItFirstOfMonth(mockMsgDate) && msgDate.After(dbDate)` will also fail in a scenario where msgDate is 1st july 2:00AM and dbDate is 1st july 1:00AM. It will always return true for every report/datapoint which comes on 1st of the month and it will cause recommender-poller service to hit kruize recommendation_api for every report coming on 1st of the month.

Yeah, yesterday while writing new example I thought about it, and thats why getDate() is putting 0 for hours, mins and seconds. So we don't take time into account and just take Date into account, this way that After func helps us,

~~~
Same date different time:
$ go run main.go 
mockDbDate 2024-01-01 00:00:00 +0000 UTC
mockMsgDate 2024-01-01 01:00:00.000000001 +0000 UTC

DB date timed to 00:00 2024-01-01 00:00:00 +0000 UTC
Msg date timed to 00:00 2024-01-01 00:00:00 +0000 UTC
###################################################

Exactly same date and time:
aupadhye@fedora ~/work/go-playground/time-test $ go run main.go 
mockDbDate 2024-01-01 00:00:00 +0000 UTC
mockMsgDate 2024-01-01 00:00:00 +0000 UTC

DB date timed to 00:00 2024-01-01 00:00:00 +0000 UTC
Msg date timed to 00:00 2024-01-01 00:00:00 +0000 UTC
~~~

**Review by upadhyeammit — APPROVED** [review]
LGTM! thanks for unit tests as well!

**Comment by yash2189** [comment]
Testing complete for this card

**Pull request merged**
